package com.holcim.altimetrik.android.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.holcim.altimetrik.android.model.OutstandingFeedback;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table OUTSTANDING_FEEDBACK.
*/
public class OutstandingFeedbackDao extends AbstractDao<OutstandingFeedback, Long> {

    public static final String TABLENAME = "OUTSTANDING_FEEDBACK";

    /**
     * Properties of entity OutstandingFeedback.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SalesforceId = new Property(1, String.class, "salesforceId", false, "SALESFORCE_ID");
        public final static Property Description = new Property(2, String.class, "description", false, "DESCRIPTION");
        public final static Property Status = new Property(3, String.class, "status", false, "STATUS");
        public final static Property Complaint = new Property(4, Boolean.class, "complaint", false, "COMPLAINT");
        public final static Property Category = new Property(5, String.class, "category", false, "CATEGORY");
        public final static Property SalesforceAccountId = new Property(6, String.class, "salesforceAccountId", false, "SALESFORCE_ACCOUNT_ID");
        public final static Property SalesforceProspectId = new Property(7, String.class, "salesforceProspectId", false, "SALESFORCE_PROSPECT_ID");
        public final static Property AccountId = new Property(8, long.class, "accountId", false, "ACCOUNT_ID");
        public final static Property ProspectId = new Property(9, long.class, "prospectId", false, "PROSPECT_ID");
    };

    private DaoSession daoSession;

    private Query<OutstandingFeedback> account_OutstandingFeedbacksQuery;
    private Query<OutstandingFeedback> prospect_OutstandingFeedbacksQuery;

    public OutstandingFeedbackDao(DaoConfig config) {
        super(config);
    }
    
    public OutstandingFeedbackDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'OUTSTANDING_FEEDBACK' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'SALESFORCE_ID' TEXT," + // 1: salesforceId
                "'DESCRIPTION' TEXT," + // 2: description
                "'STATUS' TEXT," + // 3: status
                "'COMPLAINT' INTEGER," + // 4: complaint
                "'CATEGORY' TEXT," + // 5: category
                "'SALESFORCE_ACCOUNT_ID' TEXT," + // 6: salesforceAccountId
                "'SALESFORCE_PROSPECT_ID' TEXT," + // 7: salesforceProspectId
                "'ACCOUNT_ID' INTEGER NOT NULL ," + // 8: accountId
                "'PROSPECT_ID' INTEGER NOT NULL );"); // 9: prospectId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'OUTSTANDING_FEEDBACK'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, OutstandingFeedback entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String salesforceId = entity.getSalesforceId();
        if (salesforceId != null) {
            stmt.bindString(2, salesforceId);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(3, description);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(4, status);
        }
 
        Boolean complaint = entity.getComplaint();
        if (complaint != null) {
            stmt.bindLong(5, complaint ? 1l: 0l);
        }
 
        String category = entity.getCategory();
        if (category != null) {
            stmt.bindString(6, category);
        }
 
        String salesforceAccountId = entity.getSalesforceAccountId();
        if (salesforceAccountId != null) {
            stmt.bindString(7, salesforceAccountId);
        }
 
        String salesforceProspectId = entity.getSalesforceProspectId();
        if (salesforceProspectId != null) {
            stmt.bindString(8, salesforceProspectId);
        }
        stmt.bindLong(9, entity.getAccountId());
        stmt.bindLong(10, entity.getProspectId());
    }

    @Override
    protected void attachEntity(OutstandingFeedback entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public OutstandingFeedback readEntity(Cursor cursor, int offset) {
        OutstandingFeedback entity = new OutstandingFeedback( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // salesforceId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // description
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // status
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // complaint
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // category
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // salesforceAccountId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // salesforceProspectId
            cursor.getLong(offset + 8), // accountId
            cursor.getLong(offset + 9) // prospectId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, OutstandingFeedback entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSalesforceId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDescription(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStatus(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setComplaint(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setCategory(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSalesforceAccountId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSalesforceProspectId(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setAccountId(cursor.getLong(offset + 8));
        entity.setProspectId(cursor.getLong(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(OutstandingFeedback entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(OutstandingFeedback entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "outstandingFeedbacks" to-many relationship of Account. */
    public List<OutstandingFeedback> _queryAccount_OutstandingFeedbacks(long accountId) {
        synchronized (this) {
            if (account_OutstandingFeedbacksQuery == null) {
                QueryBuilder<OutstandingFeedback> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AccountId.eq(null));
                account_OutstandingFeedbacksQuery = queryBuilder.build();
            }
        }
        Query<OutstandingFeedback> query = account_OutstandingFeedbacksQuery.forCurrentThread();
        query.setParameter(0, accountId);
        return query.list();
    }

    /** Internal query to resolve the "outstandingFeedbacks" to-many relationship of Prospect. */
    public List<OutstandingFeedback> _queryProspect_OutstandingFeedbacks(long prospectId) {
        synchronized (this) {
            if (prospect_OutstandingFeedbacksQuery == null) {
                QueryBuilder<OutstandingFeedback> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ProspectId.eq(null));
                prospect_OutstandingFeedbacksQuery = queryBuilder.build();
            }
        }
        Query<OutstandingFeedback> query = prospect_OutstandingFeedbacksQuery.forCurrentThread();
        query.setParameter(0, prospectId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAccountDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getProspectDao().getAllColumns());
            builder.append(" FROM OUTSTANDING_FEEDBACK T");
            builder.append(" LEFT JOIN ACCOUNT T0 ON T.'ACCOUNT_ID'=T0.'_id'");
            builder.append(" LEFT JOIN PROSPECT T1 ON T.'PROSPECT_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected OutstandingFeedback loadCurrentDeep(Cursor cursor, boolean lock) {
        OutstandingFeedback entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Account account = loadCurrentOther(daoSession.getAccountDao(), cursor, offset);
         if(account != null) {
            entity.setAccount(account);
        }
        offset += daoSession.getAccountDao().getAllColumns().length;

        Prospect prospect = loadCurrentOther(daoSession.getProspectDao(), cursor, offset);
         if(prospect != null) {
            entity.setProspect(prospect);
        }

        return entity;    
    }

    public OutstandingFeedback loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<OutstandingFeedback> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<OutstandingFeedback> list = new ArrayList<OutstandingFeedback>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<OutstandingFeedback> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<OutstandingFeedback> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
