package com.holcim.altimetrik.android.model;

import com.holcim.altimetrik.android.model.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import org.json.JSONException;
import org.json.JSONObject;
import com.holcim.altimetrik.android.exception.HolcimException;
import com.holcim.altimetrik.android.utilities.HolcimConsts;
// KEEP INCLUDES END
/**
 * Entity mapped to table TELE_SALE.
 */
public class TeleSale {

    private Long id;
    private String preOrderDate;
    private String salesforceId;
    private Double preOrderQuantity;
    private String product;
    private String unit;
    private String reasonForNotOrdering;
    private long accountId;
    private long prospectId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient TeleSaleDao myDao;

    private Account account;
    private Long account__resolvedKey;

    private Prospect prospect;
    private Long prospect__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TeleSale() {
    }

    public TeleSale(Long id) {
        this.id = id;
    }

    public TeleSale(Long id, String preOrderDate, String salesforceId, Double preOrderQuantity, String product, String unit, String reasonForNotOrdering, long accountId, long prospectId) {
        this.id = id;
        this.preOrderDate = preOrderDate;
        this.salesforceId = salesforceId;
        this.preOrderQuantity = preOrderQuantity;
        this.product = product;
        this.unit = unit;
        this.reasonForNotOrdering = reasonForNotOrdering;
        this.accountId = accountId;
        this.prospectId = prospectId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getTeleSaleDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPreOrderDate() {
        return preOrderDate;
    }

    public void setPreOrderDate(String preOrderDate) {
        this.preOrderDate = preOrderDate;
    }

    public String getSalesforceId() {
        return salesforceId;
    }

    public void setSalesforceId(String salesforceId) {
        this.salesforceId = salesforceId;
    }

    public Double getPreOrderQuantity() {
        return preOrderQuantity;
    }

    public void setPreOrderQuantity(Double preOrderQuantity) {
        this.preOrderQuantity = preOrderQuantity;
    }

    public String getProduct() {
        return product;
    }

    public void setProduct(String product) {
        this.product = product;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getReasonForNotOrdering() {
        return reasonForNotOrdering;
    }

    public void setReasonForNotOrdering(String reasonForNotOrdering) {
        this.reasonForNotOrdering = reasonForNotOrdering;
    }

    public long getAccountId() {
        return accountId;
    }

    public void setAccountId(long accountId) {
        this.accountId = accountId;
    }

    public long getProspectId() {
        return prospectId;
    }

    public void setProspectId(long prospectId) {
        this.prospectId = prospectId;
    }

    /** To-one relationship, resolved on first access. */
    public Account getAccount() {
        long __key = this.accountId;
        if (account__resolvedKey == null || !account__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            AccountDao targetDao = daoSession.getAccountDao();
            Account accountNew = targetDao.load(__key);
            synchronized (this) {
                account = accountNew;
            	account__resolvedKey = __key;
            }
        }
        return account;
    }

    public void setAccount(Account account) {
        if (account == null) {
            throw new DaoException("To-one property 'accountId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.account = account;
            accountId = account.getId();
            account__resolvedKey = accountId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Prospect getProspect() {
        long __key = this.prospectId;
        if (prospect__resolvedKey == null || !prospect__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ProspectDao targetDao = daoSession.getProspectDao();
            Prospect prospectNew = targetDao.load(__key);
            synchronized (this) {
                prospect = prospectNew;
            	prospect__resolvedKey = __key;
            }
        }
        return prospect;
    }

    public void setProspect(Prospect prospect) {
        if (prospect == null) {
            throw new DaoException("To-one property 'prospectId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.prospect = prospect;
            prospectId = prospect.getId();
            prospect__resolvedKey = prospectId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    
    public JSONObject toJSON() throws HolcimException {
    	try {
			JSONObject jsonObj = new JSONObject();
			jsonObj.putOpt("salesforceId", this.salesforceId);
			jsonObj.putOpt("preOrderDate", this.preOrderDate);
			jsonObj.putOpt("preOrderVolume", this.preOrderQuantity);
			jsonObj.putOpt("product", this.product);
			jsonObj.putOpt("unit", this.unit);
			jsonObj.putOpt("reasonForNotOrdering", this.reasonForNotOrdering);
			if (this.getAccount() != null) {
				jsonObj.putOpt("account", this.getAccount().getSalesforceId());
			}
			if (this.getProspect() != null) {
				jsonObj.putOpt("prospect", this.getProspect().getSalesforceId());
			}
			
			return jsonObj;
    	} catch (JSONException e) {
			throw new HolcimException(HolcimException.PARSE_EXCEPTION, HolcimConsts.ERROR_PARSING_JSON_STATUS, e.getMessage());
		}
    }
    // KEEP METHODS END

}
